import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { pathToFileURL } from "node:url";

const releasePattern = /^[0-9a-f]{40}-[1-9][0-9]*-[1-9][0-9]*$/;
const shaPattern = /^[0-9a-f]{40}$/;
const serviceName = "wavekb-next-preview.service";

function requireValue(condition, message) { if (!condition) throw new Error(message); }
function paths(options, releaseId) {
  requireValue(releasePattern.test(releaseId), "Invalid release identity");
  const applicationRoot = fs.realpathSync(options.applicationRoot);
  requireValue(applicationRoot !== "/", "Unsafe application root");
  return {
    applicationRoot, releasesRoot: path.join(applicationRoot, "releases"),
    current: path.join(applicationRoot, "current"),
    releaseDir: path.join(applicationRoot, "releases", releaseId),
    backup: path.join(options.backupRoot, releaseId),
    metadata: path.join(options.backupRoot, releaseId, "rollback.json"),
  };
}
function saveMetadata(file, value) {
  const temporary = `${file}.new`;
  fs.writeFileSync(temporary, JSON.stringify(value, null, 2) + "\n", { mode: 0o600 });
  fs.renameSync(temporary, file);
}
function replaceCurrent(current, target) {
  const temporary = `${current}.new`;
  requireValue(!fs.existsSync(temporary), "Unfinished current-link transaction requires operator review");
  fs.symlinkSync(target, temporary);
  fs.renameSync(temporary, current);
}
function checkArchive(archive) {
  const entries = execFileSync("tar", ["-tzf", archive], { encoding: "utf8" }).split("\n").filter(Boolean);
  requireValue(entries.length > 0 && entries.every((entry) => !entry.startsWith("/") && !entry.split("/").includes("..")), "Unsafe release archive");
}
async function requireHealth(options, version) {
  const health = await options.health(version);
  requireValue(health?.ok === true && health.deployment === version, "Deployment health/version check failed");
}

export async function activate(options) {
  requireValue(shaPattern.test(options.sha) && shaPattern.test(options.baseSha), "Invalid candidate or live base SHA");
  requireValue(/^[a-z_][a-z0-9_-]*$/.test(options.deployUser), "Invalid service user");
  const releaseId = `${options.sha}-${options.runId}-${options.runAttempt}`;
  const p = paths(options, releaseId);
  requireValue(!fs.existsSync(p.releaseDir) && !fs.existsSync(p.backup), "Release identity already exists; use a new run attempt");
  requireValue(fs.lstatSync(p.current).isSymbolicLink(), "Current service must be a symlink before automated deployment");
  const previousRelease = fs.realpathSync(p.current);
  requireValue(path.dirname(previousRelease) === p.releasesRoot, "Previous release is outside the managed releases directory");
  requireValue(fs.existsSync(options.environmentFile), "Existing environment file is required; never generated by deployment");
  requireValue(fs.existsSync(options.unitFile), "Existing service unit is required for exact rollback");
  await requireHealth(options, options.baseSha);
  const previousActive = await options.service("is-active");
  const previousEnabled = await options.service("is-enabled");
  requireValue(previousActive === "active", "Previous service must be healthy and active");
  checkArchive(options.archive);

  fs.mkdirSync(p.releaseDir, { recursive: false, mode: 0o755 });
  fs.chmodSync(p.releaseDir, 0o755);
  fs.mkdirSync(p.backup, { recursive: true, mode: 0o750 });
  // Preserve the complete old runtime, including .next/static and public assets.
  const archiveBackup = path.join(p.backup, "previous-release.tar.gz");
  execFileSync("tar", ["-czf", archiveBackup, "-C", previousRelease, "."]);
  fs.chmodSync(archiveBackup, 0o600);
  checkArchive(archiveBackup);
  fs.copyFileSync(options.unitFile, path.join(p.backup, "previous.service"));
  const previousUnitMode = fs.statSync(options.unitFile).mode & 0o777;
  fs.chmodSync(path.join(p.backup, "previous.service"), 0o600);
  const state = { releaseId, sha: options.sha, releaseDir: p.releaseDir, previousRelease, previousVersion: options.baseSha, previousActive, previousEnabled, previousUnitMode, phase: "prepared" };
  saveMetadata(p.metadata, state);

  try {
    execFileSync("tar", ["-xzf", options.archive, "-C", p.releaseDir, "--no-same-owner"]);
    requireValue(fs.existsSync(path.join(p.releaseDir, "apps/web/server.js")), "Candidate server is missing");
    requireValue(fs.statSync(path.join(p.releaseDir, "apps/web/.next/static")).isDirectory(), "Candidate static assets are missing");
    // Next's image optimizer writes .next/cache/images at runtime. Keep that
    // writable state outside the root-owned immutable code and static release.
    const runtimeRoot = path.join(p.applicationRoot, "runtime");
    if (!fs.existsSync(runtimeRoot)) {
      fs.mkdirSync(runtimeRoot, { mode: 0o755 }); fs.chmodSync(runtimeRoot, 0o755);
    }
    requireValue(fs.realpathSync(runtimeRoot) === runtimeRoot && fs.statSync(runtimeRoot).isDirectory(), "Unsafe runtime cache root");
    const cacheDir = path.join(runtimeRoot, releaseId);
    const cacheLink = path.join(p.releaseDir, "apps/web/.next/cache");
    requireValue(!fs.existsSync(cacheLink), "Standalone candidate must omit mutable runtime cache");
    fs.mkdirSync(cacheDir, { mode: 0o750 }); fs.chmodSync(cacheDir, 0o750);
    await options.ownCache(cacheDir, options.deployUser);
    fs.symlinkSync(cacheDir, cacheLink);
    fs.writeFileSync(path.join(p.releaseDir, "DEPLOYMENT_VERSION"), options.sha + "\n", { flag: "wx", mode: 0o644 });
    fs.writeFileSync(path.join(p.releaseDir, "start-release.sh"), `#!/bin/sh\nexport DEPLOYMENT_VERSION='${options.sha}'\nexec /usr/bin/node apps/web/server.js\n`, { flag: "wx", mode: 0o755 });
    fs.chmodSync(path.join(p.releaseDir, "DEPLOYMENT_VERSION"), 0o644);
    fs.chmodSync(path.join(p.releaseDir, "start-release.sh"), 0o755);
    const unit = `[Unit]\nDescription=WaveKB Next.js production\nAfter=network-online.target\nWants=network-online.target\n\n[Service]\nType=simple\nUser=${options.deployUser}\nWorkingDirectory=${p.current}\nEnvironmentFile=${options.environmentFile}\nExecStart=${p.current}/start-release.sh\nRestart=on-failure\nRestartSec=5\nTimeoutStopSec=20\nNoNewPrivileges=true\nPrivateTmp=true\nProtectSystem=strict\nProtectHome=true\nReadWritePaths=${p.applicationRoot}\nUMask=0027\n\n[Install]\nWantedBy=multi-user.target\n`;
    // Arm durable rollback before changing the service file or current link.
    state.phase = "activating"; saveMetadata(p.metadata, state);
    fs.writeFileSync(options.unitFile, unit, { mode: 0o644 });
    replaceCurrent(p.current, p.releaseDir);
    await options.service("daemon-reload");
    await options.service("restart");
    await requireHealth(options, options.sha);
    state.phase = "awaiting-acceptance"; saveMetadata(p.metadata, state);
    return { releaseId, releaseDir: p.releaseDir };
  } catch (error) {
    await rollback({ ...options, releaseId });
    throw error;
  }
}

export async function rollbackAccepted(options) {
  return rollback({ ...options, acceptedRollback: true });
}

export async function rollback(options) {
  const p = paths(options, options.releaseId);
  if (options.acceptedRollback) requireValue(fs.existsSync(p.metadata), "Accepted rollback metadata is missing");
  if (!fs.existsSync(p.metadata)) return; // No production mutation was armed.
  const state = JSON.parse(fs.readFileSync(p.metadata, "utf8"));
  if (options.acceptedRollback) {
    requireValue(state.phase === "accepted", "Explicit rollback requires an accepted release");
    requireValue(shaPattern.test(options.confirmedPreviousVersion) && options.confirmedPreviousVersion === state.previousVersion, "Previous SHA confirmation is missing or incorrect");
  } else if (state.phase === "rolled-back" || state.phase === "accepted") return;
  requireValue(state.releaseId === options.releaseId && state.releaseDir === p.releaseDir, "Invalid rollback metadata");
  requireValue(path.dirname(state.previousRelease) === p.releasesRoot && state.previousRelease !== p.releaseDir, "Unsafe previous release in rollback metadata");
  requireValue(shaPattern.test(state.previousVersion), "Missing exact previous version metadata");
  if (state.phase === "prepared") {
    state.phase = "rolled-back"; saveMetadata(p.metadata, state);
    return; // Candidate extraction failed before any service mutation.
  }
  const current = fs.realpathSync(p.current);
  if (options.acceptedRollback) requireValue(current === p.releaseDir, "The exact candidate must still be current for accepted rollback");
  requireValue(current === p.releaseDir || current === state.previousRelease, "Another release is current; refusing to overwrite it");
  requireValue(fs.existsSync(path.join(p.backup, "previous.service")), "Previous service backup is missing");
  if (!fs.existsSync(state.previousRelease)) {
    checkArchive(path.join(p.backup, "previous-release.tar.gz"));
    fs.mkdirSync(state.previousRelease, { mode: 0o755 });
    execFileSync("tar", ["-xzf", path.join(p.backup, "previous-release.tar.gz"), "-C", state.previousRelease]);
  }
  // Explicit authorization has passed. Persist recovery intent before touching
  // the service so an interrupted restoration can resume with normal rollback.
  state.phase = "rolling-back"; saveMetadata(p.metadata, state);
  fs.copyFileSync(path.join(p.backup, "previous.service"), options.unitFile);
  fs.chmodSync(options.unitFile, state.previousUnitMode);
  replaceCurrent(p.current, state.previousRelease);
  await options.service("daemon-reload");
  await options.service(state.previousActive === "active" ? "restart" : "stop");
  if (state.previousActive === "active") await requireHealth(options, state.previousVersion);
  state.phase = "rolled-back"; saveMetadata(p.metadata, state);
}

export async function finalize(options) {
  requireValue(options.accepted === true, "External acceptance must succeed before finalize");
  const p = paths(options, options.releaseId);
  const state = JSON.parse(fs.readFileSync(p.metadata, "utf8"));
  requireValue(state.phase === "awaiting-acceptance", "Release is not awaiting acceptance");
  const current = fs.realpathSync(p.current);
  requireValue(current === p.releaseDir, "Another release is current; refusing cleanup");
  await requireHealth(options, state.sha);
  state.phase = "accepted"; saveMetadata(p.metadata, state);
  for (const entry of fs.readdirSync(p.releasesRoot, { withFileTypes: true })) {
    if (!entry.isDirectory() || !releasePattern.test(entry.name)) continue;
    const candidate = path.join(p.releasesRoot, entry.name);
    if (candidate === current || candidate === state.previousRelease) continue;
    if (fs.statSync(candidate).mtimeMs < Date.now() - 14 * 86400_000) fs.rmSync(candidate, { recursive: true });
  }
  // Backup and rollback metadata are intentionally retained; no env or gateway cleanup.
}

async function main() {
  const [command, sha, runId, runAttempt, argument5, argument6, baseSha] = process.argv.slice(2);
  if (command === "rollback-accepted") requireValue(argument5 === "--confirm-previous-version", "Explicit previous SHA confirmation flag is required");
  const deployUser = command === "activate" ? argument5 : undefined;
  const archive = command === "activate" ? argument6 : undefined;
  const options = {
    sha, runId, runAttempt, deployUser, archive, baseSha,
    confirmedPreviousVersion: command === "rollback-accepted" ? argument6 : undefined,
    releaseId: `${sha}-${runId}-${runAttempt}`, accepted: command === "finalize",
    applicationRoot: "/srv/wavekb-next-preview",
    backupRoot: "/var/backups/wavekb-next-production",
    unitFile: "/etc/systemd/system/wavekb-next-preview.service",
    environmentFile: "/etc/wavekb/next-preview.env",
    ownCache: async (directory, user) => {
      const uid = Number(execFileSync("id", ["-u", user], { encoding: "utf8" }).trim());
      const gid = Number(execFileSync("id", ["-g", user], { encoding: "utf8" }).trim());
      requireValue(Number.isInteger(uid) && Number.isInteger(gid), "Service cache owner could not be resolved");
      fs.chownSync(directory, uid, gid);
    },
    service: async (action) => {
      const args = action === "daemon-reload" ? [action] : [action, serviceName];
      return execFileSync("systemctl", args, { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim();
    },
    health: async (expectedVersion) => {
      for (let attempt = 0; attempt < 12; attempt++) {
        try {
          const response = await fetch("http://127.0.0.1:3100/api/health", { signal: AbortSignal.timeout(5000) });
          if (response.ok) {
            const health = await response.json();
            if (health.ok === true && health.deployment === expectedVersion) return health;
          }
        } catch { /* Startup can temporarily refuse connections; never print payloads. */ }
        await new Promise((resolve) => setTimeout(resolve, 2000));
      }
      throw new Error("Local health endpoint did not become available");
    },
  };
  requireValue(["activate", "rollback", "rollback-accepted", "finalize"].includes(command), "Expected activate, rollback, rollback-accepted or finalize");
  await ({ activate, rollback, "rollback-accepted": rollbackAccepted, finalize }[command])(options);
  console.log(`Release ${command} completed.`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch(() => { console.error("Release transaction failed; retained backup metadata requires review. No environment values are logged."); process.exitCode = 1; });
}
