begin;

create table if not exists public.mentor_profiles (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid unique references public.profiles(id) on delete set null,
  display_name text not null check (char_length(display_name) between 2 and 40),
  headline text not null default '',
  bio text not null default '',
  avatar_url text,
  specialties text[] not null default '{}',
  credentials text[] not null default '{}',
  languages text[] not null default array['中文']::text[],
  verification_label text not null default '平台认证老师',
  active boolean not null default false,
  sort_order integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mentor_offers (
  id uuid primary key default gen_random_uuid(),
  mentor_id uuid not null references public.mentor_profiles(id) on delete cascade,
  name text not null check (char_length(name) between 2 and 80),
  description text not null default '',
  price_cents integer not null check (price_cents >= 0),
  currency text not null default 'CNY' check (char_length(currency) = 3),
  duration_days integer not null default 30 check (duration_days between 1 and 366),
  weekly_questions integer not null default 3 check (weekly_questions between 1 and 100),
  active boolean not null default true,
  sort_order integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mentor_orders (
  id uuid primary key default gen_random_uuid(),
  buyer_id uuid not null references public.profiles(id) on delete restrict,
  mentor_id uuid not null references public.mentor_profiles(id) on delete restrict,
  offer_id uuid not null references public.mentor_offers(id) on delete restrict,
  amount_cents integer not null check (amount_cents >= 0),
  currency text not null check (char_length(currency) = 3),
  status text not null default 'pending'
    check (status in ('pending', 'paid', 'cancelled', 'refunded', 'failed')),
  payment_provider text,
  provider_order_id text,
  idempotency_key uuid not null default gen_random_uuid(),
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (payment_provider, provider_order_id),
  unique (idempotency_key)
);

create table if not exists public.mentor_entitlements (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.mentor_orders(id) on delete restrict,
  student_id uuid not null references public.profiles(id) on delete restrict,
  mentor_id uuid not null references public.mentor_profiles(id) on delete restrict,
  weekly_question_limit integer not null check (weekly_question_limit between 1 and 100),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  status text not null default 'active'
    check (status in ('active', 'expired', 'revoked', 'refunded')),
  created_at timestamptz not null default now()
);

create table if not exists public.mentor_payment_events (
  event_id text primary key,
  provider text not null,
  event_type text not null,
  order_id uuid references public.mentor_orders(id) on delete set null,
  received_at timestamptz not null default now()
);

create table if not exists public.mentor_threads (
  id uuid primary key default gen_random_uuid(),
  entitlement_id uuid not null unique references public.mentor_entitlements(id) on delete restrict,
  student_id uuid not null references public.profiles(id) on delete restrict,
  mentor_id uuid not null references public.mentor_profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mentor_messages (
  id bigint generated by default as identity primary key,
  thread_id uuid not null references public.mentor_threads(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete restrict,
  body text not null check (char_length(body) between 1 and 5000),
  message_kind text not null check (message_kind in ('question', 'reply', 'system')),
  counts_quota boolean not null default false,
  quota_week date,
  created_at timestamptz not null default now()
);

create index if not exists mentor_profiles_catalog_idx
  on public.mentor_profiles(active, sort_order, created_at);
create index if not exists mentor_offers_catalog_idx
  on public.mentor_offers(mentor_id, active, sort_order);
create index if not exists mentor_orders_buyer_idx
  on public.mentor_orders(buyer_id, created_at desc);
create index if not exists mentor_entitlements_student_idx
  on public.mentor_entitlements(student_id, status, ends_at);
create index if not exists mentor_messages_thread_idx
  on public.mentor_messages(thread_id, created_at);
create index if not exists mentor_messages_quota_idx
  on public.mentor_messages(thread_id, quota_week)
  where counts_quota = true;

create or replace function public.mentor_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
  );
$$;

revoke all on function public.mentor_is_admin() from public;
grant execute on function public.mentor_is_admin() to authenticated;

alter table public.mentor_profiles enable row level security;
alter table public.mentor_offers enable row level security;
alter table public.mentor_orders enable row level security;
alter table public.mentor_entitlements enable row level security;
alter table public.mentor_payment_events enable row level security;
alter table public.mentor_threads enable row level security;
alter table public.mentor_messages enable row level security;

drop policy if exists mentor_profiles_admin_all on public.mentor_profiles;
create policy mentor_profiles_admin_all
on public.mentor_profiles
for all
to authenticated
using (public.mentor_is_admin())
with check (public.mentor_is_admin());

drop policy if exists mentor_offers_admin_all on public.mentor_offers;
create policy mentor_offers_admin_all
on public.mentor_offers
for all
to authenticated
using (public.mentor_is_admin())
with check (public.mentor_is_admin());

drop policy if exists mentor_orders_buyer_read on public.mentor_orders;
create policy mentor_orders_buyer_read
on public.mentor_orders
for select
to authenticated
using (buyer_id = auth.uid() or public.mentor_is_admin());

drop policy if exists mentor_orders_admin_write on public.mentor_orders;
create policy mentor_orders_admin_write
on public.mentor_orders
for all
to authenticated
using (public.mentor_is_admin())
with check (public.mentor_is_admin());

drop policy if exists mentor_entitlements_participant_read on public.mentor_entitlements;
create policy mentor_entitlements_participant_read
on public.mentor_entitlements
for select
to authenticated
using (
  student_id = auth.uid()
  or exists (
    select 1 from public.mentor_profiles
    where mentor_profiles.id = mentor_entitlements.mentor_id
      and mentor_profiles.owner_id = auth.uid()
  )
  or public.mentor_is_admin()
);

drop policy if exists mentor_payment_events_admin_read on public.mentor_payment_events;
create policy mentor_payment_events_admin_read
on public.mentor_payment_events
for select
to authenticated
using (public.mentor_is_admin());

drop policy if exists mentor_threads_participant_read on public.mentor_threads;
create policy mentor_threads_participant_read
on public.mentor_threads
for select
to authenticated
using (
  student_id = auth.uid()
  or exists (
    select 1 from public.mentor_profiles
    where mentor_profiles.id = mentor_threads.mentor_id
      and mentor_profiles.owner_id = auth.uid()
  )
  or public.mentor_is_admin()
);

drop policy if exists mentor_messages_participant_read on public.mentor_messages;
create policy mentor_messages_participant_read
on public.mentor_messages
for select
to authenticated
using (
  exists (
    select 1
    from public.mentor_threads
    left join public.mentor_profiles
      on mentor_profiles.id = mentor_threads.mentor_id
    where mentor_threads.id = mentor_messages.thread_id
      and (
        mentor_threads.student_id = auth.uid()
        or mentor_profiles.owner_id = auth.uid()
        or public.mentor_is_admin()
      )
  )
);

create or replace function public.list_mentor_catalog()
returns table (
  mentor_id uuid,
  display_name text,
  headline text,
  bio text,
  avatar_url text,
  specialties text[],
  credentials text[],
  languages text[],
  verification_label text,
  offers jsonb
)
language sql
stable
security definer
set search_path = public
as $$
  select
    m.id,
    m.display_name,
    m.headline,
    m.bio,
    m.avatar_url,
    m.specialties,
    m.credentials,
    m.languages,
    m.verification_label,
    coalesce(
      jsonb_agg(
        jsonb_build_object(
          'id', o.id,
          'name', o.name,
          'description', o.description,
          'price_cents', o.price_cents,
          'currency', o.currency,
          'duration_days', o.duration_days,
          'weekly_questions', o.weekly_questions,
          'active', o.active
        )
        order by o.sort_order, o.created_at
      ) filter (where o.id is not null and o.active),
      '[]'::jsonb
    )
  from public.mentor_profiles m
  left join public.mentor_offers o on o.mentor_id = m.id
  where m.active
  group by m.id
  order by m.sort_order, m.created_at;
$$;

create or replace function public.get_mentor_detail(p_mentor_id uuid)
returns table (
  mentor_id uuid,
  display_name text,
  headline text,
  bio text,
  avatar_url text,
  specialties text[],
  credentials text[],
  languages text[],
  verification_label text,
  offers jsonb
)
language sql
stable
security definer
set search_path = public
as $$
  select catalog.*
  from public.list_mentor_catalog() catalog
  where catalog.mentor_id = p_mentor_id;
$$;

revoke all on function public.list_mentor_catalog() from public;
revoke all on function public.get_mentor_detail(uuid) from public;
grant execute on function public.list_mentor_catalog() to anon, authenticated;
grant execute on function public.get_mentor_detail(uuid) to anon, authenticated;

create or replace function public.create_mentor_order(p_offer_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  selected_offer public.mentor_offers%rowtype;
  new_order_id uuid;
begin
  if auth.uid() is null then
    raise exception 'authentication_required';
  end if;
  select *
  into selected_offer
  from public.mentor_offers
  where id = p_offer_id
    and active;
  if selected_offer.id is null then
    raise exception 'offer_unavailable';
  end if;
  if not exists (
    select 1 from public.mentor_profiles
    where id = selected_offer.mentor_id
      and active
  ) then
    raise exception 'mentor_unavailable';
  end if;
  insert into public.mentor_orders (
    buyer_id,
    mentor_id,
    offer_id,
    amount_cents,
    currency
  )
  values (
    auth.uid(),
    selected_offer.mentor_id,
    selected_offer.id,
    selected_offer.price_cents,
    upper(selected_offer.currency)
  )
  returning id into new_order_id;
  return new_order_id;
end;
$$;

revoke all on function public.create_mentor_order(uuid) from public;
grant execute on function public.create_mentor_order(uuid) to authenticated;

create or replace function public.activate_paid_mentor_order()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  selected_offer public.mentor_offers%rowtype;
  entitlement_id uuid;
begin
  if new.status = 'paid' and old.status is distinct from 'paid' then
    select * into selected_offer
    from public.mentor_offers
    where id = new.offer_id;

    insert into public.mentor_entitlements (
      order_id,
      student_id,
      mentor_id,
      weekly_question_limit,
      starts_at,
      ends_at,
      status
    )
    values (
      new.id,
      new.buyer_id,
      new.mentor_id,
      selected_offer.weekly_questions,
      coalesce(new.paid_at, now()),
      coalesce(new.paid_at, now()) + make_interval(days => selected_offer.duration_days),
      'active'
    )
    on conflict (order_id) do update set
      status = 'active',
      starts_at = excluded.starts_at,
      ends_at = excluded.ends_at
    returning id into entitlement_id;

    insert into public.mentor_threads (
      entitlement_id,
      student_id,
      mentor_id
    )
    values (entitlement_id, new.buyer_id, new.mentor_id)
    on conflict (entitlement_id) do nothing;
  elsif new.status in ('refunded', 'cancelled') and old.status = 'paid' then
    update public.mentor_entitlements
    set status = case when new.status = 'refunded' then 'refunded' else 'revoked' end
    where order_id = new.id;
  end if;
  return new;
end;
$$;

drop trigger if exists mentor_orders_activate_after_payment on public.mentor_orders;
create trigger mentor_orders_activate_after_payment
after update of status on public.mentor_orders
for each row
execute function public.activate_paid_mentor_order();

create or replace function public.list_my_mentor_access()
returns table (
  entitlement_id uuid,
  mentor_id uuid,
  mentor_name text,
  mentor_avatar_url text,
  thread_id uuid,
  status text,
  weekly_question_limit integer,
  questions_used bigint,
  starts_at timestamptz,
  ends_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    e.id,
    e.mentor_id,
    m.display_name,
    m.avatar_url,
    t.id,
    case
      when e.status = 'active' and e.ends_at > now() then 'active'
      when e.status = 'active' then 'expired'
      else e.status
    end,
    e.weekly_question_limit,
    (
      select count(*)
      from public.mentor_messages message
      where message.thread_id = t.id
        and message.counts_quota
        and message.quota_week = date_trunc('week', now())::date
    ),
    e.starts_at,
    e.ends_at
  from public.mentor_entitlements e
  join public.mentor_profiles m on m.id = e.mentor_id
  join public.mentor_threads t on t.entitlement_id = e.id
  where e.student_id = auth.uid()
  order by e.created_at desc;
$$;

create or replace function public.get_mentor_thread(p_thread_id uuid)
returns table (
  thread_id uuid,
  mentor_id uuid,
  mentor_name text,
  mentor_avatar_url text,
  student_id uuid,
  status text,
  weekly_question_limit integer,
  questions_used bigint,
  starts_at timestamptz,
  ends_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    t.id,
    t.mentor_id,
    m.display_name,
    m.avatar_url,
    t.student_id,
    case
      when e.status = 'active' and e.ends_at > now() then 'active'
      when e.status = 'active' then 'expired'
      else e.status
    end,
    e.weekly_question_limit,
    (
      select count(*)
      from public.mentor_messages message
      where message.thread_id = t.id
        and message.counts_quota
        and message.quota_week = date_trunc('week', now())::date
    ),
    e.starts_at,
    e.ends_at
  from public.mentor_threads t
  join public.mentor_entitlements e on e.id = t.entitlement_id
  join public.mentor_profiles m on m.id = t.mentor_id
  where t.id = p_thread_id
    and (
      t.student_id = auth.uid()
      or m.owner_id = auth.uid()
      or public.mentor_is_admin()
    );
$$;

create or replace function public.list_mentor_messages(p_thread_id uuid)
returns table (
  id bigint,
  sender_id uuid,
  body text,
  message_kind text,
  created_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select message.id, message.sender_id, message.body, message.message_kind, message.created_at
  from public.mentor_messages message
  where message.thread_id = p_thread_id
    and exists (
      select 1
      from public.mentor_threads t
      join public.mentor_profiles m on m.id = t.mentor_id
      where t.id = p_thread_id
        and (
          t.student_id = auth.uid()
          or m.owner_id = auth.uid()
          or public.mentor_is_admin()
        )
    )
  order by message.created_at;
$$;

create or replace function public.send_mentor_message(
  p_thread_id uuid,
  p_body text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  selected_thread public.mentor_threads%rowtype;
  selected_entitlement public.mentor_entitlements%rowtype;
  selected_mentor public.mentor_profiles%rowtype;
  is_student boolean;
  used_count bigint;
  new_message_id bigint;
  clean_body text := btrim(coalesce(p_body, ''));
begin
  if auth.uid() is null then
    raise exception 'authentication_required';
  end if;
  if char_length(clean_body) < 5 or char_length(clean_body) > 5000 then
    raise exception 'invalid_message';
  end if;

  select * into selected_thread
  from public.mentor_threads
  where id = p_thread_id;
  select * into selected_entitlement
  from public.mentor_entitlements
  where id = selected_thread.entitlement_id;
  select * into selected_mentor
  from public.mentor_profiles
  where id = selected_thread.mentor_id;

  is_student := selected_thread.student_id = auth.uid();
  if not is_student
    and selected_mentor.owner_id is distinct from auth.uid()
    and not public.mentor_is_admin() then
    raise exception 'thread_access_denied';
  end if;

  if is_student then
    if selected_entitlement.status <> 'active'
      or selected_entitlement.ends_at <= now() then
      raise exception 'tutoring_access_expired';
    end if;
    select count(*) into used_count
    from public.mentor_messages
    where thread_id = p_thread_id
      and counts_quota
      and quota_week = date_trunc('week', now())::date;
    if used_count >= selected_entitlement.weekly_question_limit then
      raise exception 'weekly_question_limit_reached';
    end if;
  end if;

  insert into public.mentor_messages (
    thread_id,
    sender_id,
    body,
    message_kind,
    counts_quota,
    quota_week
  )
  values (
    p_thread_id,
    auth.uid(),
    clean_body,
    case when is_student then 'question' else 'reply' end,
    is_student,
    case when is_student then date_trunc('week', now())::date else null end
  )
  returning id into new_message_id;

  update public.mentor_threads
  set updated_at = now()
  where id = p_thread_id;

  return new_message_id;
end;
$$;

revoke all on function public.list_my_mentor_access() from public;
revoke all on function public.get_mentor_thread(uuid) from public;
revoke all on function public.list_mentor_messages(uuid) from public;
revoke all on function public.send_mentor_message(uuid, text) from public;
grant execute on function public.list_my_mentor_access() to authenticated;
grant execute on function public.get_mentor_thread(uuid) to authenticated;
grant execute on function public.list_mentor_messages(uuid) to authenticated;
grant execute on function public.send_mentor_message(uuid, text) to authenticated;

grant select, insert, update, delete on public.mentor_profiles to authenticated;
grant select, insert, update, delete on public.mentor_offers to authenticated;
grant select, insert, update, delete on public.mentor_orders to authenticated;
grant select on public.mentor_entitlements to authenticated;
grant select on public.mentor_threads to authenticated;
grant select on public.mentor_messages to authenticated;
grant select on public.mentor_payment_events to authenticated;

commit;
